In [44]:
from randomuser import RandomUser
import pandas as pd

In [45]:
r = RandomUser()

In [46]:
some_list = r.generate_users(10)

In [47]:
print(some_list)

[<randomuser.RandomUser object at 0x000002039CF018D0>, <randomuser.RandomUser object at 0x000002039CF02750>, <randomuser.RandomUser object at 0x000002039CFAD8D0>, <randomuser.RandomUser object at 0x000002039CFAD940>, <randomuser.RandomUser object at 0x000002039D053B90>, <randomuser.RandomUser object at 0x000002039D053BF0>, <randomuser.RandomUser object at 0x000002039D053C50>, <randomuser.RandomUser object at 0x000002039D053CB0>, <randomuser.RandomUser object at 0x000002039D053D10>, <randomuser.RandomUser object at 0x000002039D053D70>]

In [48]:
name = r.get_full_name()

In [49]:
print(name)

Katie Caldwell

In [50]:
for user in some_list:
    print(user.get_full_name() , user.get_email())

Lyna Louis lyna.louis@example.com
Hartwig Obst hartwig.obst@example.com
Katherine Herrera katherine.herrera@example.com
درسا علیزاده drs.aalyzdh@example.com
Noel Martins noel.martins@example.com
Emmi Lampinen emmi.lampinen@example.com
Ülkü Topçuoğlu ulku.topcuoglu@example.com
Wallace Gibson wallace.gibson@example.com
Gökhan Limoncuoğlu gokhan.limoncuoglu@example.com
Juho Halla juho.halla@example.com

In [51]:
for user in some_list:
    print(user.get_picture())

https://randomuser.me/api/portraits/women/21.jpg
https://randomuser.me/api/portraits/men/76.jpg
https://randomuser.me/api/portraits/women/84.jpg
https://randomuser.me/api/portraits/women/71.jpg
https://randomuser.me/api/portraits/men/80.jpg
https://randomuser.me/api/portraits/women/50.jpg
https://randomuser.me/api/portraits/women/51.jpg
https://randomuser.me/api/portraits/men/53.jpg
https://randomuser.me/api/portraits/men/72.jpg
https://randomuser.me/api/portraits/men/90.jpg

In [52]:
def get_users():
    users = []

    for user in RandomUser.generate_users(10):
        users.append({
            "Name": user.get_full_name(),
            "Gender": user.get_gender(),
            "City":user.get_city(),
            "State":user.get_state(),
            "Email":user.get_email(),
            "DOB":user.get_dob(),
            "Picture":user.get_picture()
        })
    return pd.DataFrame(users)

df1 = get_users()

df1.head()

,Name,Gender,City,State,Email,DOB,Picture
0,Moises Vermunt,male,Broekhuizen Lb,Groningen,moises.vermunt@example.com,1962-05-09T23:38:32.096Z,https://randomuser.me/api/portraits/men/23.jpg
1,Coline Noel,female,Grenoble,Isère,coline.noel@example.com,1989-09-16T21:33:42.546Z,https://randomuser.me/api/portraits/women/69.jpg
2,آنیتا یاسمی,female,ارومیه,تهران,anyt.ysmy@example.com,1968-08-20T09:39:36.111Z,https://randomuser.me/api/portraits/women/6.jpg
3,Mathias Sanchez,male,Tours,Somme,mathias.sanchez@example.com,1970-02-09T21:59:10.666Z,https://randomuser.me/api/portraits/men/12.jpg
4,Imogen Thompson,female,Auckland,Northland,imogen.thompson@example.com,1987-09-15T10:53:25.765Z,https://randomuser.me/api/portraits/women/13.jpg

In [53]:
# Fruityvice API

In [54]:
import requests
import json

In [55]:
data = requests.get("https://web.archive.org/web/20240929211114/https://fruityvice.com/api/fruit/all")
print(data)

<Response [200]>

In [56]:
results = json.loads(data.text)
print(results)

[{'name': 'Persimmon', 'id': 52, 'family': 'Ebenaceae', 'order': 'Rosales', 'genus': 'Diospyros', 'nutritions': {'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'carbohydrates': 18.0, 'protein': 0.0}}, {'name': 'Strawberry', 'id': 3, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Fragaria', 'nutritions': {'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'carbohydrates': 5.5, 'protein': 0.8}}, {'name': 'Banana', 'id': 1, 'family': 'Musaceae', 'order': 'Zingiberales', 'genus': 'Musa', 'nutritions': {'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'carbohydrates': 22.0, 'protein': 1.0}}, {'name': 'Tomato', 'id': 5, 'family': 'Solanaceae', 'order': 'Solanales', 'genus': 'Solanum', 'nutritions': {'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'carbohydrates': 3.9, 'protein': 0.9}}, {'name': 'Pear', 'id': 4, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Pyrus', 'nutritions': {'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'carbohydrates': 15.0, 'protein': 0.4}}, {'name': 'Durian', 'id': 60, 'family': 'Malvaceae', 'order': 'Malvales', 'genus': 'Durio', 'nutritions': {'calories': 147, 'fat': 5.3, 'sugar': 6.75, 'carbohydrates': 27.1, 'protein': 1.5}}, {'name': 'Blackberry', 'id': 64, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Rubus', 'nutritions': {'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'carbohydrates': 9.0, 'protein': 1.3}}, {'name': 'Lingonberry', 'id': 65, 'family': 'Ericaceae', 'order': 'Ericales', 'genus': 'Vaccinium', 'nutritions': {'calories': 50, 'fat': 0.34, 'sugar': 5.74, 'carbohydrates': 11.3, 'protein': 0.75}}, {'name': 'Kiwi', 'id': 66, 'family': 'Actinidiaceae', 'order': 'Struthioniformes', 'genus': 'Apteryx', 'nutritions': {'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'carbohydrates': 15.0, 'protein': 1.1}}, {'name': 'Lychee', 'id': 67, 'family': 'Sapindaceae', 'order': 'Sapindales', 'genus': 'Litchi', 'nutritions': {'calories': 66, 'fat': 0.44, 'sugar': 15.0, 'carbohydrates': 17.0, 'protein': 0.8}}, {'name': 'Pineapple', 'id': 10, 'family': 'Bromeliaceae', 'order': 'Poales', 'genus': 'Ananas', 'nutritions': {'calories': 50, 'fat': 0.12, 'sugar': 9.85, 'carbohydrates': 13.12, 'protein': 0.54}}, {'name': 'Fig', 'id': 68, 'family': 'Moraceae', 'order': 'Rosales', 'genus': 'Ficus', 'nutritions': {'calories': 74, 'fat': 0.3, 'sugar': 16.0, 'carbohydrates': 19.0, 'protein': 0.8}}, {'name': 'Gooseberry', 'id': 69, 'family': 'Grossulariaceae', 'order': 'Saxifragales', 'genus': 'Ribes', 'nutritions': {'calories': 44, 'fat': 0.6, 'sugar': 0.0, 'carbohydrates': 10.0, 'protein': 0.9}}, {'name': 'Passionfruit', 'id': 70, 'family': 'Passifloraceae', 'order': 'Malpighiales', 'genus': 'Passiflora', 'nutritions': {'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'carbohydrates': 22.4, 'protein': 2.2}}, {'name': 'Plum', 'id': 71, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Prunus', 'nutritions': {'calories': 46, 'fat': 0.28, 'sugar': 9.92, 'carbohydrates': 11.4, 'protein': 0.7}}, {'name': 'Orange', 'id': 2, 'family': 'Rutaceae', 'order': 'Sapindales', 'genus': 'Citrus', 'nutritions': {'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'carbohydrates': 8.3, 'protein': 1.0}}, {'name': 'GreenApple', 'id': 72, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Malus', 'nutritions': {'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'carbohydrates': 3.1, 'protein': 0.4}}, {'name': 'Raspberry', 'id': 23, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Rubus', 'nutritions': {'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'carbohydrates': 12.0, 'protein': 1.2}}, {'name': 'Watermelon', 'id': 25, 'family': 'Cucurbitaceae', 'order': 'Cucurbitales', 'genus': 'Citrullus', 'nutritions': {'calories': 30, 'fat': 0.2, 'sugar': 6.0, 'carbohydrates': 8.0, 'protein': 0.6}}, {'name': 'Lemon', 'id': 26, 'family': 'Rutaceae', 'order': 'Sapindales', 'genus': 'Citrus', 'nutritions': {'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'carbohydrates': 9.0, 'protein': 1.1}}, {'name': 'Mango', 'id': 27, 'family': 'Anacardiaceae', 'order': 'Sapindales', 'genus': 'Mangifera', 'nutritions': {'calories': 60, 'fat': 0.38, 'sugar': 13.7, 'carbohydrates': 15.0, 'protein': 0.82}}, {'name': 'Blueberry', 'id': 33, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Fragaria', 'nutritions': {'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'carbohydrates': 5.5, 'protein': 0.0}}, {'name': 'Apple', 'id': 6, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Malus', 'nutritions': {'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'carbohydrates': 11.4, 'protein': 0.3}}, {'name': 'Guava', 'id': 37, 'family': 'Myrtaceae', 'order': 'Myrtales', 'genus': 'Psidium', 'nutritions': {'calories': 68, 'fat': 1.0, 'sugar': 9.0, 'carbohydrates': 14.0, 'protein': 2.6}}, {'name': 'Apricot', 'id': 35, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Prunus', 'nutritions': {'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'carbohydrates': 3.9, 'protein': 0.5}}, {'name': 'Melon', 'id': 41, 'family': 'Cucurbitaceae', 'order': 'Cucurbitaceae', 'genus': 'Cucumis', 'nutritions': {'calories': 34, 'fat': 0.0, 'sugar': 8.0, 'carbohydrates': 8.0, 'protein': 0.0}}, {'name': 'Tangerine', 'id': 77, 'family': 'Rutaceae', 'order': 'Sapindales', 'genus': 'Citrus', 'nutritions': {'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'carbohydrates': 8.3, 'protein': 0.0}}, {'name': 'Pitahaya', 'id': 78, 'family': 'Cactaceae', 'order': 'Caryophyllales', 'genus': 'Cactaceae', 'nutritions': {'calories': 36, 'fat': 0.4, 'sugar': 3.0, 'carbohydrates': 7.0, 'protein': 1.0}}, {'name': 'Lime', 'id': 44, 'family': 'Rutaceae', 'order': 'Sapindales', 'genus': 'Citrus', 'nutritions': {'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'carbohydrates': 8.4, 'protein': 0.3}}, {'name': 'Pomegranate', 'id': 79, 'family': 'Lythraceae', 'order': 'Myrtales', 'genus': 'Punica', 'nutritions': {'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'carbohydrates': 18.7, 'protein': 1.7}}, {'name': 'Dragonfruit', 'id': 80, 'family': 'Cactaceae', 'order': 'Caryophyllales', 'genus': 'Selenicereus', 'nutritions': {'calories': 60, 'fat': 1.5, 'sugar': 8.0, 'carbohydrates': 9.0, 'protein': 9.0}}, {'name': 'Grape', 'id': 81, 'family': 'Vitaceae', 'order': 'Vitales', 'genus': 'Vitis', 'nutritions': {'calories': 69, 'fat': 0.16, 'sugar': 16.0, 'carbohydrates': 18.1, 'protein': 0.72}}, {'name': 'Morus', 'id': 82, 'family': 'Moraceae', 'order': 'Rosales', 'genus': 'Morus', 'nutritions': {'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'carbohydrates': 9.8, 'protein': 1.44}}, {'name': 'Feijoa', 'id': 76, 'family': 'Myrtaceae', 'order': 'Myrtoideae', 'genus': 'Sellowiana', 'nutritions': {'calories': 44, 'fat': 0.4, 'sugar': 3.0, 'carbohydrates': 8.0, 'protein': 0.6}}, {'name': 'Avocado', 'id': 84, 'family': 'Lauraceae', 'order': 'Laurales', 'genus': 'Persea', 'nutritions': {'calories': 160, 'fat': 14.66, 'sugar': 0.66, 'carbohydrates': 8.53, 'protein': 2.0}}, {'name': 'Kiwifruit', 'id': 85, 'family': 'Actinidiaceae', 'order': 'Ericales', 'genus': 'Actinidia', 'nutritions': {'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'carbohydrates': 14.6, 'protein': 1.14}}, {'name': 'Cranberry', 'id': 87, 'family': 'Ericaceae', 'order': 'Ericales', 'genus': 'Vaccinium', 'nutritions': {'calories': 46, 'fat': 0.1, 'sugar': 4.0, 'carbohydrates': 12.2, 'protein': 0.4}}, {'name': 'Cherry', 'id': 9, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Prunus', 'nutritions': {'calories': 50, 'fat': 0.3, 'sugar': 8.0, 'carbohydrates': 12.0, 'protein': 1.0}}, {'name': 'Peach', 'id': 86, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Prunus', 'nutritions': {'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'carbohydrates': 9.5, 'protein': 0.9}}, {'name': 'Jackfruit', 'id': 94, 'family': 'Moraceae', 'order': 'Rosales', 'genus': 'Artocarpus', 'nutritions': {'calories': 95, 'fat': 0.0, 'sugar': 19.1, 'carbohydrates': 23.2, 'protein': 1.72}}, {'name': 'Horned Melon', 'id': 95, 'family': 'Cucurbitaceae', 'order': 'Cucurbitales', 'genus': 'Cucumis', 'nutritions': {'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'carbohydrates': 7.56, 'protein': 1.78}}, {'name': 'Hazelnut', 'id': 96, 'family': 'Betulaceae', 'order': 'Fagales', 'genus': 'Corylus', 'nutritions': {'calories': 628, 'fat': 61.0, 'sugar': 4.3, 'carbohydrates': 17.0, 'protein': 15.0}}, {'name': 'Pomelo', 'id': 98, 'family': 'Rutaceae', 'order': 'Sapindales', 'genus': 'Citrus', 'nutritions': {'calories': 37, 'fat': 0.0, 'sugar': 8.5, 'carbohydrates': 9.67, 'protein': 0.82}}, {'name': 'Mangosteen', 'id': 99, 'family': 'Clusiaceae', 'order': 'Malpighiales', 'genus': 'Garcinia', 'nutritions': {'calories': 73, 'fat': 0.58, 'sugar': 16.11, 'carbohydrates': 17.91, 'protein': 0.41}}, {'name': 'Pumpkin', 'id': 100, 'family': 'Cucurbitaceae', 'order': 'Cucurbitales', 'genus': 'Cucurbita', 'nutritions': {'calories': 25, 'fat': 0.3, 'sugar': 3.3, 'carbohydrates': 4.6, 'protein': 1.1}}, {'name': 'Japanese Persimmon', 'id': 101, 'family': ' Ebenaceae', 'order': ' Ericales', 'genus': 'Diospyros', 'nutritions': {'calories': 70, 'fat': 0.2, 'sugar': 13.0, 'carbohydrates': 19.0, 'protein': 0.6}}, {'name': 'Papaya', 'id': 42, 'family': 'Caricaceae', 'order': 'Brassicales', 'genus': 'Carica', 'nutritions': {'calories': 39, 'fat': 0.3, 'sugar': 4.4, 'carbohydrates': 5.8, 'protein': 0.5}}, {'name': 'Annona', 'id': 103, 'family': 'Annonaceae', 'order': 'Rosales', 'genus': 'Annonas', 'nutritions': {'calories': 92, 'fat': 0.29, 'sugar': 3.4, 'carbohydrates': 19.1, 'protein': 1.5}}, {'name': 'Ceylon Gooseberry', 'id': 104, 'family': 'Salicaceae', 'order': 'Malpighiales', 'genus': 'Dovyalis', 'nutritions': {'calories': 47, 'fat': 0.3, 'sugar': 8.1, 'carbohydrates': 9.6, 'protein': 1.2}}]

In [57]:
df2 = pd.DataFrame(results)

In [58]:
df2.head()

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."

In [59]:
df3 = pd.json_normalize(results)

In [60]:
df3.head()

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.0,18.0,18.0,0.0
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.4,5.4,5.5,0.8
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.2,17.2,22.0,1.0
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.2,2.6,3.9,0.9
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.1,10.0,15.0,0.4

In [61]:
cherry = df3.loc[df3['name'] == 'Cherry']

In [62]:
cherry.iloc[0]['family']

'Rosaceae'

In [63]:
cherry.iloc[0]['order']

'Rosales'

In [64]:
cal_banana = df3.loc[df3["name"] == 'Banana']

In [65]:
df4 = pd.DataFrame(cal_banana)
df4

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.2,17.2,22.0,1.0

In [66]:
print(cal_banana.iloc[0]['nutritions.calories'])

96

In [67]:
# Official Joke API

In [68]:
data2 = requests.get("https://official-joke-api.appspot.com/jokes/ten")

In [69]:
results = json.loads(data2.text)

In [72]:
df4 = pd.json_normalize(results)
df4

,type,setup,punchline,id
0,programming,How many programmers does it take to change a ...,None that's a hardware problem,24
1,general,Did you hear about the crime in the parking ga...,It was wrong on so many levels.,394
2,general,Why didn't the number 4 get into the nightclub?,Because he is 2 square.,337
3,general,What does an angry pepper do?,It gets jalapeño face.,236
4,general,Did you hear about the chameleon who couldn't ...,They had a reptile dysfunction.,85
5,general,Where was the Declaration of Independence signed?,At the bottom!,293
6,general,What do you call an alligator in a vest?,An in-vest-igator!,217
7,programming,What did the router say to the doctor?,It hurts when IP.,366
8,general,Why do bears have hairy coats?,Fur protection.,341
9,general,If you boil a clown...,Do you get a laughing stock?,44

In [73]:
df4.drop(columns=['type' , 'id'] , inplace=True)

In [74]:
df4

,setup,punchline
0,How many programmers does it take to change a ...,None that's a hardware problem
1,Did you hear about the crime in the parking ga...,It was wrong on so many levels.
2,Why didn't the number 4 get into the nightclub?,Because he is 2 square.
3,What does an angry pepper do?,It gets jalapeño face.
4,Did you hear about the chameleon who couldn't ...,They had a reptile dysfunction.
5,Where was the Declaration of Independence signed?,At the bottom!
6,What do you call an alligator in a vest?,An in-vest-igator!
7,What did the router say to the doctor?,It hurts when IP.
8,Why do bears have hairy coats?,Fur protection.
9,If you boil a clown...,Do you get a laughing stock?